// getgif actions
export const GET_TRENDING_GIFS = 'GET_TRENDING_GIFS'
export const ERROR_GETTING_GIFS = 'ERROR_GETTING_GIFS'
export const SEARCH_GIFS = 'SEARCH_GIFS'
export const PREVIOUS_SEARCH = 'PREVIOUS_SEARCH'
